# prepare could be done in before_script of build depending on solution/product
# package could be done in before_script of deploy depending on solution/product
# cleanup could be done in after_script of deploy depending on solution/product
stages:
  - prepare
  - build
  - test
  - package
  - deploy
  - cleanup

include:
  - local: .gitlab/ci/build.gitlab-ci.yml
  - local: .gitlab/ci/test.gitlab-ci.yml
  - local: .gitlab/ci/productX.gitlab-ci.yml

# Define variables - they should be agnostic to this script
# variables:

# Define any steps that should be done before or after every job
# before_script:
#
# after_script:
#


# base job features for versioning; CD
.version:
  stage: prepare
  allow_failure: true
  artifacts:
    expire_in: 1 hour

# base job features for packaging; CI/CD
.package:
  stage: package
  only:
    refs:
      - master
  artifacts:
    expire_in: 1 day

# base job features for deploy; CI/CD
.deploy:
  stage: deploy
  only:
    refs:
      - master

# base job for tagging a release
.tag
  stage: cleanup
