# by solution, always
variables:
 - MAVEN_CLI_OPTS = "--errors --batch-mode"

.compile
  tags:
    - maven
  # before_script:
  #   - # add any global steps here
  # after_script:
  #   - # removed any global added secrets here
  artifacts:
    expire_in: 1 hour

.core:compile
  extends: .compile
  stage: core:build

.sample:compile
  extends: .compile
  stage: sample:build

compile_core:
  extends: .core:compile
  script:
    - mvn $MAVEN_OPTS $MAVEN_CLI_OPTS -f gocwebtemplate-core/pom.xml clean compile

compile_jsp_samples:
  extends: .sample:compile
  script:
    - mvn $MAVEN_OPTS $MAVEN_CLI_OPTS -f gocwebtemplate-sample-jsp/pom.xml clean compile

compile_spring_samples:
  extends: .sample:compile
  script:
    - mvn $MAVEN_OPTS $MAVEN_CLI_OPTS -f gocwebtemplate-sample-spring/pom.xml clean compile
