# by solution, always

.compile:
  tags:
    - maven
  # before_script:
  #   - # add any global steps here
  # after_script:
  #   - # removed any global added secrets here
  artifacts:
    expire_in: 1 hour

.compile:core:
  extends: .compile
  stage: core:build

.compile:sample:
  extends: .compile
  stage: sample:build

compile:core:
  extends: .compile:core
  script:
    - mvn $MAVEN_OPTS $MAVEN_CLI_OPTS -f gocwebtemplate-core/pom.xml clean compile

compile:sample:jsp:
  extends: .compile:sample
  script:
    - mvn $MAVEN_OPTS $MAVEN_CLI_OPTS -f gocwebtemplate-sample-jsp/pom.xml clean compile

compile:sample:spring:
  extends: .compile:sample
  script:
    - mvn $MAVEN_OPTS $MAVEN_CLI_OPTS -f gocwebtemplate-sample-spring/pom.xml clean compile
