# by product, CI/CD
# might merge with deploy

.package:
  stage: package
  dependencies:
    - compile_slnX
  only:
    refs:
      - master
  artifacts:
    expire_in: 1 day

package_productX:
  extends: .package
  only:
    variables:
      - $PRODUCTX_VERSION != null
  depends:
    - version_productX
  script:
    - #script to update package the product
  artifacts:
    name: # name the artifacts with the product name
    paths:
      - #path to final product
