# per project / test type;

.test
  tags:
    - maven

.unit_test:sample:
  extends: .test
  stage: sample:test

unit_test:core:
  extends: .test
  stage: core:test
  dependencies: 
    - compile:core
  script:
    - mvn $MAVEN_OPTS $MAVEN_CLI_OPTS -f gocwebtemplate-core/pom.xml test
  artifacts:
    reports:
      junit: # path to the junit export of the test results

unit_test:sample:jsp:
  extends: .unit_test:sample
  dependencies: 
    - compile:sample:jsp
  script:
    - mvn $MAVEN_OPTS $MAVEN_CLI_OPTS -f gocwebtemplate-sample-jsp/pom.xml test
  artifacts:
    reports:
      junit: # path to the junit export of the test results

unit_test:sample:spring:
  extends: .unit_test:sample
  dependencies: 
    - compile:sample:spring
  script:
    - mvn $MAVEN_OPTS $MAVEN_CLI_OPTS -f gocwebtemplate-sample-spring/pom.xml test
  artifacts:
    reports:
      junit: # path to the junit export of the test results

# codequality_projX
#   extends: .codequality
#   script:
#     - # execute the tests
#   artifacts:
#     reports:
#       codequality: # path to json report https://github.com/codeclimate/spec/blob/master/SPEC.md#data-types
